Update script to clone git group

diff --git a/git/git_clone_group b/git/git_clone_group
--- a/git/git_clone_group
+++ b/git/git_clone_group
@@ -2,67 +2,74 @@
 
 find_groups_id() {
   local group_name=$1
-  local tmp_file=/tmp/${group_name}_$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 6 | head -n 1).json
+  local tmp_file
+  local http_code
   local groups_id=""
   local i
 
-  local http_code=$(curl -s -w '%{http_code}' -o ${tmp_file} --header "PRIVATE-TOKEN: ${GIT_TOKEN}" ${GIT_URL}/api/v4/groups?search=${group_name})
+  tmp_file=/tmp/${group_name}_$(< /dev/urandom tr -dc 'a-zA-Z0-9' | fold -w 6 | head -n 1).json
+  http_code=$(curl -s -w '%{http_code}' -o "${tmp_file}" --header "PRIVATE-TOKEN: ${GIT_TOKEN}" "${GIT_URL}/api/v4/groups?search=${group_name}")
   if [[ "${http_code}" -ne 200 ]]; then
     echo "Unable to reach gitlab API - http error code: ${http_code}"
     return 1
-  elif [[ $(grep "\"message\"" ${tmp_file} | wc -l) -ne 0 ]]; then
-    echo "Unable to get gitlab groups id - error message: $(cat ${tmp_file} | jq .message | args)"
+  elif [[ $(grep -c "\"message\"" "${tmp_file}") -ne 0 ]]; then
+    echo "Unable to get gitlab groups id - error message: $(< "${tmp_file}" jq .message | args)"
     return 1
   fi
 
-  local group_count=$(cat ${tmp_file} | jq length)
+  local group_count
+  group_count=$(< "${tmp_file}" jq length)
   if [[ ${group_count} -eq 0 ]]; then
     echo "No group found with name ${group_name}. Please check your permission."
     return 1
   fi
 
-  for ((i = 0; i < ${group_count};i++)) {
-    local group_name_found=$(cat ${tmp_file} | jq .[${i}].name | xargs)
-    local group_id_found=$(cat ${tmp_file} | jq .[${i}].id | xargs)
+  for ((i = 0; i < group_count;i++)) {
+    local group_name_found
+    local group_id_found
+
+    group_name_found=$(< "${tmp_file}" jq .[${i}].name | xargs)
+    group_id_found=$(< "${tmp_file}" jq .[${i}].id | xargs)
     if [[ "${group_name_found}" == "${group_name}" ]]; then
       groups_id="${groups_id} ${group_id_found}"
     fi
   }
 
-  echo ${tmp_file} > /tmp/toto
-  #rm ${tmp_file}
-  echo ${groups_id}
+  echo "${groups_id}"
   return 0
 }
 
 clone_group() {
   local group_id=$1
-  local tmp_file=/tmp/${group_id}_$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 6 | head -n 1).json
   local i
-
-  local http_code=$(curl -s -w '%{http_code}' --header "PRIVATE-TOKEN: ${GIT_TOKEN}" ${GIT_URL}/api/v4/groups/${group_id}/projects?per_page=100 -o ${tmp_file})
+  local http_code
+  
+  tmp_file=/tmp/${group_id}_$(< /dev/urandom tr -dc 'a-zA-Z0-9' | fold -w 6 | head -n 1).json
+  http_code=$(curl -s -w '%{http_code}' --header "PRIVATE-TOKEN: ${GIT_TOKEN}" "${GIT_URL}/api/v4/groups/${group_id}/projects?per_page=100" -o "${tmp_file}")
   if [[ "${http_code}" -ne 200 ]]; then
     echo "Unable to reach gitlab API - http error code: ${http_code}"
     return 1
-  elif [[ $(grep "\"message\"" ${tmp_file} | wc -l) -ne 0 ]]; then
-    echo "Unable to get gitlab groups id - error message: $(cat ${tmp_file} | jq .message | args)"
+  elif [[ $(grep -c "\"message\"" "${tmp_file}") -ne 0 ]]; then
+    echo "Unable to get gitlab groups id - error message: $(< "${tmp_file}" jq .message | args)"
     return 1
   fi
 
-  local project_count=$(cat ${tmp_file} | jq length)
+  local project_count
+  project_count=$(< "${tmp_file}" jq length)
   if [[ ${project_count} -eq 0 ]]; then
     echo "No project found in this group"
     return 1
   fi
 
-  for ((i = 0; i < ${project_count};i++)) {
-    local project_name=$(cat ${tmp_file} | jq .[${i}].name | xargs)
-    local project_ssh_url=$(cat ${tmp_file} | jq .[${i}].ssh_url_to_repo | xargs)
+  for ((i = 0; i < project_count;i++)) {
+    local project_name
+    project_name=$(< "${tmp_file}" jq .[${i}].name | xargs)
+    
+    local project_ssh_url
+    project_ssh_url=$(< "${tmp_file}" jq .[${i}].ssh_url_to_repo | xargs)
     echo "Cloning project ${project_name} ..."
-    git clone -q ${project_ssh_url} > /dev/null 2>&1
+    git clone -q "${project_ssh_url}" > /dev/null 2>&1
   }
-
-  #rm ${tmp_file}
 }
 
 usage() {
@@ -70,7 +77,7 @@ usage() {
 }
 
 main() {
-  if ! which jq > /dev/null; then
+  if ! command -v jq > /dev/null; then
     echo "jq binary should be installed"
     exit 1
   fi
@@ -91,15 +98,14 @@ main() {
   fi
 
   echo "Finding groups id with name $1..."
-  groups_id=$(find_groups_id $1)
-  if [[ $? -eq 0 ]]; then
+  if groups_id=$(find_groups_id "$1"); then
     echo "Groups id found with name $1: ${groups_id}"
 
-    for group in "${groups_id}"; do
-      clone_group $group
+    for group in ${groups_id}; do
+      clone_group "$group"
     done
   else
-    echo $groups_id
+    echo "$groups_id"
   fi
 }
-main $@
+main "$@"
