Update script to clone git group

diff --git a/git/git_clone_group b/git/git_clone_group
--- a/git/git_clone_group
+++ b/git/git_clone_group
@@ -6,9 +6,21 @@ find_groups_id() {
   local groups_id=""
   local i
 
-  curl -s --header "PRIVATE-TOKEN: ${GIT_TOKEN}" ${GIT_URL}/api/v4/groups?search=${group_name} -o ${tmp_file}
+  local http_code=$(curl -s -w '%{http_code}' -o ${tmp_file} --header "PRIVATE-TOKEN: ${GIT_TOKEN}" ${GIT_URL}/api/v4/groups?search=${group_name})
+  if [[ "${http_code}" -ne 200 ]]; then
+    echo "Unable to reach gitlab API - http error code: ${http_code}"
+    return 1
+  elif [[ $(grep "\"message\"" ${tmp_file} | wc -l) -ne 0 ]]; then
+    echo "Unable to get gitlab groups id - error message: $(cat ${tmp_file} | jq .message | args)"
+    return 1
+  fi
 
   local group_count=$(cat ${tmp_file} | jq length)
+  if [[ ${group_count} -eq 0 ]]; then
+    echo "No group found with name ${group_name}. Please check your permission."
+    return 1
+  fi
+
   for ((i = 0; i < ${group_count};i++)) {
     local group_name_found=$(cat ${tmp_file} | jq .[${i}].name | xargs)
     local group_id_found=$(cat ${tmp_file} | jq .[${i}].id | xargs)
@@ -17,8 +29,10 @@ find_groups_id() {
     fi
   }
 
-  rm ${tmp_file}
+  echo ${tmp_file} > /tmp/toto
+  #rm ${tmp_file}
   echo ${groups_id}
+  return 0
 }
 
 clone_group() {
@@ -26,9 +40,21 @@ clone_group() {
   local tmp_file=/tmp/${group_id}_$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 6 | head -n 1).json
   local i
 
-  curl -s --header "PRIVATE-TOKEN: ${GIT_TOKEN}" ${GIT_URL}/api/v4/groups/${group_id}/projects -o ${tmp_file}
+  local http_code=$(curl -s -w '%{http_code}' --header "PRIVATE-TOKEN: ${GIT_TOKEN}" ${GIT_URL}/api/v4/groups/${group_id}/projects?per_page=100 -o ${tmp_file})
+  if [[ "${http_code}" -ne 200 ]]; then
+    echo "Unable to reach gitlab API - http error code: ${http_code}"
+    return 1
+  elif [[ $(grep "\"message\"" ${tmp_file} | wc -l) -ne 0 ]]; then
+    echo "Unable to get gitlab groups id - error message: $(cat ${tmp_file} | jq .message | args)"
+    return 1
+  fi
 
   local project_count=$(cat ${tmp_file} | jq length)
+  if [[ ${project_count} -eq 0 ]]; then
+    echo "No project found in this group"
+    return 1
+  fi
+
   for ((i = 0; i < ${project_count};i++)) {
     local project_name=$(cat ${tmp_file} | jq .[${i}].name | xargs)
     local project_ssh_url=$(cat ${tmp_file} | jq .[${i}].ssh_url_to_repo | xargs)
@@ -36,7 +62,7 @@ clone_group() {
     git clone -q ${project_ssh_url} > /dev/null 2>&1
   }
 
-  rm ${tmp_file}
+  #rm ${tmp_file}
 }
 
 usage() {
@@ -66,11 +92,14 @@ main() {
 
   echo "Finding groups id with name $1..."
   groups_id=$(find_groups_id $1)
+  if [[ $? -eq 0 ]]; then
+    echo "Groups id found with name $1: ${groups_id}"
 
-  echo "Groups id found with name $1: ${groups_id}"
-
-  for group in "${groups_id}"; do
-    clone_group $group
-  done
+    for group in "${groups_id}"; do
+      clone_group $group
+    done
+  else
+    echo $groups_id
+  fi
 }
 main $@
